In [1]:
#installing the Numpy directly
!pip install numpy

In [2]:
#checking the numpy version
import numpy as np
print(np.__version__)

2.3.4


In [4]:
#creating array 

array1 = np.array([1,2,3,4,5])
array2 = np.array([[1,2,3,4],[5,6,7,8]])

print(array1)

print('\n')

print(array2)

[1 2 3 4 5]


[[1 2 3 4]
 [5 6 7 8]]


In [7]:

a_int8 = np.array([1,2,3], dtype = np.int8)
a_int16 = np.array([1,2,3], dtype= np.int16)
a_int32 = np.array([1,2,3], dtype = np.int32)
a_int64 = np.array([1,2,3], dtype=np.int64)

print(a_int8)
print(a_int16)
print(a_int32)
print(a_int64)

[1 2 3]
[1 2 3]
[1 2 3]
[1 2 3]


In [13]:
print(a_int64.dtype)


int64


In [14]:
a_uint8    = np.array([1,2,3], dtype=np.uint8)
a_uint16   = np.array([1,2,3], dtype=np.uint16)
a_uint32   = np.array([1,2,3], dtype=np.uint32)
a_uint64   = np.array([1,2,3], dtype=np.uint64)


a_float16  = np.array([1,2,3], dtype=np.float16)
a_float32  = np.array([1,2,3], dtype=np.float32)
a_float64  = np.array([1,2,3], dtype=np.float64)


In [12]:
print(a_uint32.dtype)
print(a_float64.dtype)

uint32
float64


In [15]:
a_complex64   = np.array([1,2,3], dtype=np.complex64)
a_complex128  = np.array([1,2,3], dtype=np.complex128)


In [16]:
print(a_complex128.dtype)

complex128


In [ ]:
string_byte = np.array(['2','3','4','5'] , dtype='S')
string_int = np.array(['2','3','4','5'] , dtype='U')
#Unicode and Byete string
print(string_byte.dtype)
print(string_int.dtype)

|S1
<U1


In [18]:
boolean_type = np.array([1,0,1,0], dtype = np.bool_)

print(boolean_type.dtype)

bool


In [20]:
obj_type = np.array([1,3,'Amir',203.4,True], dtype=object)
print(obj_type.dtype)

object


## Essential Attributes 

In [21]:
arr = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

In [25]:
#finding the shpe of the arrray 
print(arr.shape)


(2, 6)


In [26]:
#dimensihion
arr.ndim

2

In [27]:

#dtype
arr.dtype

dtype('int64')

In [28]:

#size
arr.size

12

In [29]:

#memory used
arr.nbytes

96

In [30]:
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [36]:
#Getting any element

# row 0, col 1 of upper array

print(arr[0,1])

#all rows and column 1
print(arr[:,1])

#row 0
print(arr[0,:])

#sub-array
print(arr[0:2,1:3])

2
[2 8]
[1 2 3 4 5 6]
[[2 3]
 [8 9]]


In [39]:
#Vectorized 
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [40]:
print(arr+5)

[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [41]:
print(arr-5)

[[-4 -3 -2 -1  0  1]
 [ 2  3  4  5  6  7]]


In [42]:
print(arr*2)

[[ 2  4  6  8 10 12]
 [14 16 18 20 22 24]]


In [43]:
print(arr/2)

[[0.5 1.  1.5 2.  2.5 3. ]
 [3.5 4.  4.5 5.  5.5 6. ]]


In [44]:
arr2 = np.array([[13,14,15,16,17,18],[19,20,21,22,23,24]])

In [46]:
print(arr)
print(arr2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [47]:
print(arr+arr2)

[[14 16 18 20 22 24]
 [26 28 30 32 34 36]]
