In [2]:
import numpy as np

In [3]:

# 1D Array 
array_1d = np.array([1,2,3,4,5,6])
print(array_1d.ndim)

1


In [4]:
#2D Array
array_2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(array_2d.ndim)

2


In [5]:
#3D Array
array_3d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(array_3d.ndim)

3


In [6]:
A = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
B = np.array([10,11,12])

# ADD 1D + 2D Array
C = A + B
print(C)

[[[11 13 15]
  [14 16 18]
  [17 19 21]]]


In [7]:
col = np.array([[1],[2],[3]])
row = np.array([10,20,30])

col + row

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

In [16]:
a = np.array([1,2,3])

print(a+2)
print(a-2)
print(a*10)
print(a/2)
print(a**2)
print(a**3)
print(a**4)

print('\n')

print(np.sqrt(a))
print(np.log(a))
print(np.exp(a))


[3 4 5]
[-1  0  1]
[10 20 30]
[0.5 1.  1.5]
[1 4 9]
[ 1  8 27]
[ 1 16 81]


[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]
[ 2.71828183  7.3890561  20.08553692]


In [17]:
print(A)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [19]:
print(A.sum())

45


In [20]:
print(A.mean())

5.0


In [21]:
print(A.min())

1


In [22]:
print(A.max())

9


In [24]:
print(A.std())

2.581988897471611


In [25]:
print(A.var())

6.666666666666667


In [27]:
print(np.median(A))

5.0


In [36]:
dot_a = np.array([1,2,3])
dot_b = np.array([4,5,6])

#Dot Product
print(np.dot(dot_a,dot_b))

32


In [37]:
A = np.array([[1,2],[3,4]])

B = np.array([[5,6],[7,8]])

# Matrix Multipicartion
np.matmul(A, B)

array([[19, 22],
       [43, 50]])

In [39]:
A

array([[1, 2],
       [3, 4]])

In [41]:
# Transpose
A.T

array([[1, 3],
       [2, 4]])

In [42]:
# Dertmine
np.linalg.det(A)

np.float64(-2.0000000000000004)

In [44]:
# Inverse matrix
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [46]:
# Random Interger
# Min 0, max 11, and matrix size 3 * 3
np.random.randint(0,11,size=(3,3))

array([[10,  0,  0],
       [ 9,  4,  4],
       [ 2,  4, 10]])

In [ ]:
# Max 100, min 5 , size 5*5 array

np.random.randint(5,100, size =(5,5))

array([[27, 20, 53, 58, 90],
       [96, 78, 41, 43, 18],
       [25, 85, 51, 99, 40],
       [71, 80, 97,  9, 53],
       [65, 73, 48, 93, 93]])

In [53]:
# 3 * 3 array with float 

np.random.rand(3,3)

array([[0.29200364, 0.4150342 , 0.43796051],
       [0.89563716, 0.86601851, 0.46816129],
       [0.20810196, 0.30873691, 0.32277511]])

In [55]:
# Normal Distribution

np.random.randn(3,3)

array([[ 2.22642115, -0.85221307, -0.23282817],
       [ 0.86486937,  0.12874488, -0.38785204],
       [-1.72908348,  0.08766072,  1.14241465]])

In [57]:
print(np.random.seed(42))

None


In [65]:
a 

array([5, 3, 1, 4, 2])

In [75]:
a = np.array([1,2,3,4,5])
print(a)
print(np.random.shuffle(a))


[1 2 3 4 5]
None


In [91]:
example_arr = np.random.randint(1,50, size =(1,10))
print(example_arr)

[[ 7  9 24  1 44  8 24 11 17  8]]


In [92]:
example_arr

array([[ 7,  9, 24,  1, 44,  8, 24, 11, 17,  8]])

In [94]:
np.random.choice([45, 18, 47, 24, 26, 25, 45, 41, 29, 15], size=2)

array([45, 26])