In [60]:
import numpy as np

Basic Indexing

In [61]:
a = np.array([1,2,3,4,5])

print(a[0])
print(a[1])
print(a[2])
print(a)

1
2
3
[1 2 3 4 5]


In [62]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print(arr[0,2])

3


In [63]:
arr[1]

array([4, 5, 6])

In [64]:
arr[1:2]

array([[4, 5, 6]])

In [65]:
arr[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [66]:
arr[:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
arr[::2]

array([[1, 2, 3],
       [7, 8, 9]])

In [68]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [69]:
arr[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [70]:
arr[:,0] # first row first columns

array([1, 4, 7])

In [71]:
arr[1,] # firt row

array([4, 5, 6])

In [72]:
a = np.array([10,20,30,40,50,60,75,80])

In [73]:
a>25

array([False, False,  True,  True,  True,  True,  True,  True])

In [74]:
a<25

array([ True,  True, False, False, False, False, False, False])

In [75]:
a[a>25]

array([30, 40, 50, 60, 75, 80])

In [76]:
a[(a>25)&(a<50)]

array([30, 40])

In [77]:
a[a%2==0] # No 75

array([10, 20, 30, 40, 50, 60, 80])

In [79]:
print(a)
a[[0,2,4]] # gives the index number data

[10 20 30 40 50 60 75 80]


array([10, 30, 50])

In [80]:
#2D array example
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

arr[[0,2],[1,2]] # arr[[row ],[columns]]

array([2, 9])

In [81]:
a

array([10, 20, 30, 40, 50, 60, 75, 80])

In [86]:
a[[7,4,5,0,6,2,1,3]] # Reordering

array([80, 50, 60, 10, 75, 30, 20, 40])

In [90]:
#reshaping
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [91]:
b = a.reshape(3,4)

In [89]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [98]:
#reshape auto.. just give me row or col number and rest one is -1
a.reshape(-1,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [99]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [106]:
# new axix turn 1d into 2d

a[:,np.newaxis]

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [107]:
a[np.newaxis,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [111]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [112]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [115]:
arr.flatten() # returns a copy as 1D Array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
arr.ravel() # Returns view

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [120]:
# Removing negetive number

data = np.array([1,2,-3,0,4,-5])
clean = data[data>=0]
clean

array([1, 2, 0, 4])

In [128]:
data[data<0]=0

In [130]:
data

array([1, 2, 0, 0, 4, 0])

In [132]:
marks = np.array([50, 88, 92, 40, 76, 85])
marks[marks>80]

array([88, 92, 85])

In [133]:
np.diag(arr)

array([1, 5, 9])

In [141]:
gener_arr = np.arange(20)
final_arr =gener_arr.reshape(4,5)

In [142]:
final_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [144]:
diagonal_arr_of_final = np.diag(final_arr)
diagonal_arr_of_final

array([ 0,  6, 12, 18])

In [145]:
# making a 3*4 array with int
np.random.randint(1,10,(3,4))

array([[8, 2, 7, 6],
       [3, 7, 9, 2],
       [9, 5, 4, 2]])

In [149]:
a = np.array([5,10,15,20,25,30])

a[1::2]

array([10, 20, 30])

In [150]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
arr[1:,1:]

array([[5, 6],
       [8, 9]])

In [151]:
a = np.arange(12)

In [152]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [156]:
a[:,np.newaxis]

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])