<img src="https://i.sstatic.net/hSM5G.png" width = "500" height= "">

In [1]:
# Stacking Arrays
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

np.vstack([a,b])



array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])

np.hstack([a,b])

array([1, 2, 3, 4, 5, 6])

In [3]:
np.dstack([a, b])


array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [5]:
# Array split Numpy

x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.split(x,5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [8]:
arr = np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
np.vsplit(arr,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [10]:
np.hsplit(arr,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [12]:
np.array_split(x,3)  # Does not requre Equal Size

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [13]:
# Sorting


In [32]:
x = np.array([3,2,5,6,3,6,8,0])
np.sort(x)

array([0, 2, 3, 3, 5, 6, 6, 8])

In [19]:
# Sort 2D Along Axis

arr = np.array([[3,1,2],
                [6,4,5]])
np.sort(arr,axis =0) # Column

array([[3, 1, 2],
       [6, 4, 5]])

In [20]:

np.sort(arr,axis = 1) # Row

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
x = np.array([40,20,45]) # Return the indexs for sorting
np.argsort(x)

array([1, 0, 2])

In [23]:
x = np.array([1,2,3,4,5,2,4,5,7,3,4,2,4,3,6,7,])
np.unique(x)

array([1, 2, 3, 4, 5, 6, 7])

In [24]:
np.unique(x, return_counts = True)

(array([1, 2, 3, 4, 5, 6, 7]), array([1, 3, 3, 4, 2, 1, 2]))

In [26]:
# Set Operations

a  = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
b = np.arange(11,20)
b

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [29]:
np.union1d(a,b)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [36]:
print(a)
print(x)


[0 1 2 3 4 5 6 7 8 9]
[3 2 5 6 3 6 8 0]


In [37]:
np.intersect1d(a,x)

array([0, 2, 3, 5, 6, 8])

In [38]:
np.setdiff1d(a,b)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr = np.array([[1,9,3],
                [4,2,6]])

arr.argmax()       # global index
arr.argmin()

np.int64(0)

In [48]:

arr.argmax(axis=0) # per column
# First column 4(index 1) is max, second column 9(index 0) is max and last 6 ( index 1) is max so --> 1,0,1

array([1, 0, 1])

In [49]:
arr.argmax(axis=1) # per row

array([1, 2])

In [50]:
arr = np.arange(25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [60]:
arr.sum(axis=0) # sum of each row same column element

array([50, 55, 60, 65, 70])

In [61]:
arr.sum(axis=1) # sum of row

array([ 10,  35,  60,  85, 110])

In [62]:
arr.mean(axis=0)

array([10., 11., 12., 13., 14.])

In [63]:
arr.mean(axis=1)

array([ 2.,  7., 12., 17., 22.])

In [64]:
arr.std(axis=1)

array([1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356])

In [65]:
arr.max(axis=0)

array([20, 21, 22, 23, 24])