# Matirx Algebra

In [1]:
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])


In [2]:
# Dot
print(np.dot(A,B))

[[19 22]
 [43 50]]


In [4]:
# matmul
A @ B

array([[19, 22],
       [43, 50]])

In [6]:
A

array([[1, 2],
       [3, 4]])

In [7]:
# Transpose
A.T

array([[1, 3],
       [2, 4]])

# Matrix Norms

In [9]:
x = np.array([3,4])

np.linalg.norm(x, ord=1)   # L1 norm

np.float64(7.0)

In [10]:

np.linalg.norm(x, ord=2)   # L2 norm (Euclidean)

np.float64(5.0)

In [11]:

np.linalg.norm(A, 'fro')   # Frobenius norm (matrix)


np.float64(5.477225575051661)

In [13]:
# Diterminant and Inverse Matrix
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
# Diterminant also diterminant is only possible on squrare matrix

np.linalg.det(A)


np.float64(-2.0000000000000004)

In [20]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [21]:
#EIGENVALUES & EIGENVECTORS

# Core of PCA, covariance matrix decomposition, spectral clustering.

In [23]:
eigvals, eigvecs = np.linalg.eig(A)

print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)


Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [24]:
#SINGULAR VALUE DECOMPOSITION (SVD)
U, S, Vt = np.linalg.svd(A)

print("U:", U)
print("Singular Values:", S)
print("Vt:", Vt)


U: [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
Singular Values: [5.4649857  0.36596619]
Vt: [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


# Solving Math Problem


In [25]:
A = np.array([[3,1],
              [1,2]])

b = np.array([9,8])

x = np.linalg.solve(A, b)


In [26]:
x

array([2., 3.])

In [27]:
# ML Data Preprocessing

In [30]:
# Random 100 integer as an array

rnd_array = np.random.randint(0,100, size = 100)
rnd_array

array([14, 96, 14,  0, 94, 83, 94, 93, 41, 56,  0, 47, 88, 12, 32, 84, 62,
       33, 65, 15, 86, 70, 41, 55, 47, 69, 70,  7, 79,  8, 97,  7, 10, 67,
        2, 61, 82, 39,  7,  1, 31, 28, 63, 46, 83, 73, 82, 65, 10, 44,  8,
       64, 36, 12, 22, 40, 76, 91,  5, 16, 38,  3, 99, 31, 34, 14,  9, 49,
       12, 79, 36, 25, 28, 77, 74,  2, 80, 70, 12, 45, 28, 93, 88, 54, 71,
       98, 11, 31, 34, 87, 62, 18, 44,  3, 86,  5, 26,  4, 62, 78])

In [31]:
# Standardardrization
# X_std = (X - X.mean(axis=0)) / X.std(axis=0)
# MinMax Scaling
# X_std = (X - X.mean(axis=0)) / X.std(axis=0)
# Normalize Vector (unit vector)
#x = x / np.linalg.norm(x)
# removie outliers
#X[X > X.mean() + 3*X.std()] = X.mean()
# Replacing missing values
#X = np.where(np.isnan(X), np.nanmean(X), X)

