In [6]:
import numpy as np

# Perforamnce Optimization


In [7]:
a = np.arange(10_000_000)
a

array([      0,       1,       2, ..., 9999997, 9999998, 9999999])

In [8]:
b = a*2
b

array([       0,        2,        4, ..., 19999994, 19999996, 19999998])

In [11]:
A = np.array([[1,2],[3,4]])

In [13]:
a + b

array([       0,        3,        6, ..., 29999991, 29999994, 29999997])

In [18]:
A = np.ones((5,10))

A

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [21]:
C = np.arange(20)
C

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [23]:
# Comparison: np.ones((3, 10_000_000)) vs np.arange(10_000_000)

# np.ones((3, 10_000_000))
# - Creates a 2D array with shape (3, 10,000,000)
# - All elements are 1.0
# - Default dtype: float64
# - Total elements: 30,000,000
# - Approx. memory usage: ~240 MB
# - Common use: initialization, weights, constant matrices

# np.arange(10_000_000)
# - Creates a 1D array with shape (10,000,000,)
# - Values increase sequentially from 0 to 9,999,999
# - Default dtype: int64
# - Total elements: 10,000,000
# - Approx. memory usage: ~80 MB
# - Common use: indexing, counters, sequences

# Key difference:
# - np.ones -> constant values, larger memory footprint (here)
# - np.arange -> sequential values, smaller memory footprint


In [24]:
a = np.arange(10_000_000) # same as a = np.arange(10000000) but used one is better for reading
a

array([      0,       1,       2, ..., 9999997, 9999998, 9999999])

In [25]:
A = np.ones((3,10_000_000))
A

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [26]:
A + a

array([[1.000000e+00, 2.000000e+00, 3.000000e+00, ..., 9.999998e+06,
        9.999999e+06, 1.000000e+07],
       [1.000000e+00, 2.000000e+00, 3.000000e+00, ..., 9.999998e+06,
        9.999999e+06, 1.000000e+07],
       [1.000000e+00, 2.000000e+00, 3.000000e+00, ..., 9.999998e+06,
        9.999999e+06, 1.000000e+07]])

In [27]:
np.set_printoptions(suppress=True)


In [33]:
A + a

array([[       1.,        2.,        3., ...,  9999998.,  9999999.,
        10000000.],
       [       1.,        2.,        3., ...,  9999998.,  9999999.,
        10000000.],
       [       1.,        2.,        3., ...,  9999998.,  9999999.,
        10000000.]])

In [34]:
(A + a).astype(np.int32)

array([[       1,        2,        3, ...,  9999998,  9999999, 10000000],
       [       1,        2,        3, ...,  9999998,  9999999, 10000000],
       [       1,        2,        3, ...,  9999998,  9999999, 10000000]],
      dtype=int32)

In [42]:
arr = np.random.randint(10_000_000)
arr

1909101

In [37]:
np.sqrt(arr)

np.float64(2810.4691779131826)

In [40]:
np.exp(2)

np.float64(7.38905609893065)

In [48]:
np.log(arr)

np.float64(14.462143008589642)

In [50]:
arr +=1

In [51]:
arr

1909102

In [53]:
x32 = np.array([1,2,3],dtype = np.float32)
x8 = np.array([1,2,3],dtype = np.int8)

In [54]:
x32.nbytes

12

In [55]:
x8.nbytes

3

In [59]:
x64= np.array([1,2,3],dtype = np.float64)

In [60]:
x64.nbytes

24

In [61]:
a = np.arange(6)

In [62]:
a

array([0, 1, 2, 3, 4, 5])

In [65]:
b = a.reshape(2,3)

In [66]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [67]:
c = b.ravel()

In [68]:
b[0]= 999

In [70]:
print(b)

[[999 999 999]
 [  3   4   5]]


In [71]:
print(a)

[999 999 999   3   4   5]


In [74]:
d = np.arange(6).reshape(2,3)

In [76]:
c = d.flatten()    # copy

c[1] = 555
print(d)           # a does NOT change


[[0 1 2]
 [3 4 5]]


In [77]:
import numpy as np
import time

x = np.arange(10_000_000)

t1 = time.time()
y = [i * 2 for i in x]       # Python loop (slow)
print("Python:", time.time() - t1)

t2 = time.time()
z = x * 2                     # NumPy vectorized (fast)
print("NumPy :", time.time() - t2)


Python: 1.9394443035125732
NumPy : 0.10897231101989746


# ML using way

In [78]:
import pandas as pd

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"

df = pd.read_csv(url)

df.head()


sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [81]:
# Split Features X and labels y

X = df.iloc[:, :-1]
X

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [82]:
import numpy as np

# Convert the DataFrame to a NumPy array
df_numpy = df.to_numpy()

# Perform slicing to get all rows and all columns except the last one
X_numpy = df_numpy[:, :-1]

# Display the result (first 5 rows to avoid overwhelming output)
print(X_numpy[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.0 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.0 3.6 1.4 0.2]]
