Create a 1D NumPy array from 1 to 50.


In [2]:
import numpy as np

arr = np.arange(1,51)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

Create a 5×5 matrix filled with zeros.


In [7]:
arr = np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Create a 3×4 matrix filled with ones.


In [8]:
arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Create an identity matrix of size 6.


In [10]:
arr = np.eye((6))
arr

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

Create an array of even numbers from 2 to 100.



In [13]:
arr = np.arange(2,100,2)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

Create an array of 20 equally spaced numbers between 0 and 1.


In [16]:
arr = np.linspace(0,1,20)
arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

Create an array of 15 random integers between 10 and 50.


In [20]:
arr = np.random.randint(10,50, size = 15)
arr

array([41, 32, 32, 27, 38, 37, 13, 26, 35, 22, 14, 44, 31, 17, 36])

Create a float32 array from 1 to 10.


In [24]:
arr = np.arange(1,11, dtype = np.float32)
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

Create an int8 array from 1 to 10.


In [25]:
arr = np.arange( 1,11, dtype = np.int8)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

Create a boolean array from a list.


In [26]:
arr = np.array([True, True, False, True, False],dtype=np.bool)
arr

array([ True,  True, False,  True, False])

Convert an integer array to float.


In [27]:
arr = np.array([1,2,3,4,5])
arr_float = arr.astype(np.float32)
arr_float

array([1., 2., 3., 4., 5.], dtype=float32)

Create a complex number array


In [28]:
arr = np.array([1+2j,2+2J, 3-2j])
arr

array([1.+2.j, 2.+2.j, 3.-2.j])

Create a datetime64 array of 7 consecutive days


In [29]:
arr = np.arange('2025-01-01', '2025-01-08', dtype='datetime64[D]')
arr

array(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
       '2025-01-05', '2025-01-06', '2025-01-07'], dtype='datetime64[D]')

Check dtype, shape, size of an array

In [34]:
arr = np.arange(1,17,1).reshape(4,4)
print(arr.dtype)
print(arr.size)
print(arr.shape)

int64
16
(4, 4)


Change dtype without modifying original array

In [37]:
arr = np.array([1,2,3,4,5,6,0,1,0,1,3,0])
new_arr = arr.astype(bool)

new_arr

array([ True,  True,  True,  True,  True,  True, False,  True, False,
        True,  True, False])

Create an empty array and fill it later

In [40]:
arr = []
arr[:] = [1,2,3,4,5,6,6,7,8,9,0,23,234,5,65,778,54453,34]
arr

[1, 2, 3, 4, 5, 6, 6, 7, 8, 9, 0, 23, 234, 5, 65, 778, 54453, 34]

Create a constant array filled with value 9

In [42]:
arr = np.full((4,4),9)
arr

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

Compare memory size of int32 vs int64 arrays

In [44]:
arr32 = np.array([1,2,3],dtype=np.int32)
arr64 = np.array([1,2,3],dtype = np.int64)\

print(arr32.nbytes)
print(arr64.nbytes)

12
24


Copy an array and verify independence

In [46]:
a = np.array([1,2,3])
b = a.copy()
b[2]=2

b


array([1, 2, 2])

Create a range array using arange

In [47]:
arr = np.arange(0,20,2)

arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])