# NumPy Practice – Day 2

Topic: Broadcasting, Math Operations, and Random

Instructions:
- Read each question carefully.
- Write your solution in the code cell below each question.
- Do not modify the questions.

## Question 1
Add a scalar to a 2D array.

In [1]:
# Write your code here

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
final = arr + 1

print(final)

## Question 2
Multiply a vector with a matrix using broadcasting.

In [4]:
# Write your code here

arr1 = np.array([4, 5, 6])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

arr1*arr2 

array([[28, 40, 54],
       [40, 55, 72]])

## Question 3
Add a row vector to a matrix.

In [5]:
# Write your code here

arr = np.array([[1, 2, 3], [4, 5, 6]])
arr1 = np.array([4, 5, 6])

reasults = arr + arr1
print(reasults)

[[ 5  7  9]
 [ 8 10 12]]


## Question 4
Add a column vector to a matrix.

In [8]:
# Write your code here

arr = np.array([[1,2,3],[4,5,6]]) # 2,3
col_vector = np.array([[10],[20]])

arr + col_vector



array([[11, 12, 13],
       [24, 25, 26]])

## Question 5
Convert Celsius to Fahrenheit using broadcasting.

In [10]:
# Write your code here

C = np.array([10,20,30,40,50,60,70])

F = (9/5) * C + 32

print(F)

[ 50.  68.  86. 104. 122. 140. 158.]


## Question 6
Normalize an array using broadcasting.

In [12]:
# Write your code here

import numpy as np

X = np.array([10, 20, 30, 40, 50,60])

X_norm = (X - X.min()) / (X.max() - X.min())

print(X_norm)


[0.  0.2 0.4 0.6 0.8 1. ]


## Question 7
Square all elements using vectorization.

In [13]:
# Write your code here
X = np.array([1,2,3,4,5,6,7,8,9])
x_sq = np.square(X)
x_sq

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [14]:
X_sq = X **2
X_sq

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

## Question 8
Apply sqrt, log, exp to an array.

In [ ]:
# Write your code here

## Question 9
Compute element-wise max between two arrays.

In [ ]:
# Write your code here

## Question 10
Generate a 5×5 random float matrix.

In [ ]:
# Write your code here

## Question 11
Generate 1000 samples from normal distribution.

In [ ]:
# Write your code here

## Question 12
Generate 500 samples from Poisson distribution.

In [ ]:
# Write your code here

## Question 13
Set a random seed and reproduce results.

In [ ]:
# Write your code here

## Question 14
Shuffle a 1D array.

In [ ]:
# Write your code here

## Question 15
Randomly choose elements with probabilities.

In [ ]:
# Write your code here

## Question 16
Clip values between 0 and 1.

In [ ]:
# Write your code here

## Question 17
Use np.where to replace values.

In [ ]:
# Write your code here

## Question 18
Compute absolute values.

In [ ]:
# Write your code here

## Question 19
Round values to 2 decimals.

In [ ]:
# Write your code here

## Question 20
Compare performance of loop vs vectorized operation.

In [ ]:
# Write your code here